server:
  port: 8081
spring:
  datasource:
    username: demo
    password: '123'
    url: jdbc:mysql://127.0.0.1:3306/student?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: studentSystem
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      metadata:
#        version:v1
#      config:
#        file-extension: yaml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher